version: "3.7"
services:
  first_write:
    image: 'bitnami/postgresql:latest'
    # user: 1001:1001 bitnami/postgresql is always non-root
    container_name: write
    ports:
      - 127.0.0.1:9000:5432
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replication_user
      - POSTGRESQL_REPLICATION_PASSWORD=replication_password
      - POSTGRESQL_USERNAME=database_user
      - POSTGRESQL_PASSWORD=database_password
      - POSTGRESQL_DATABASE=testdb
      # Only the superuser "postgres" can execute "CREATE EXTENSION IF NOT EXISTS "pgcrypto";" if needed for having UUIDs
      # Superuser needs a password set here
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      # To see direct actions on the database while examining read and write behavior:
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=remote_apply # Safest method for data consistency
    networks:
      - net


  first_read_1:
    image: 'bitnami/postgresql:latest'
    container_name: read1
    ports:
      - 127.0.0.1:9001:5432
    depends_on:
      - first_write
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replication_user
      - POSTGRESQL_REPLICATION_PASSWORD=replication_password
      - POSTGRESQL_MASTER_HOST=localhost
      - POSTGRESQL_PASSWORD=database_password
      - POSTGRESQL_MASTER_PORT_NUMBER=9000
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
    networks:
      - net


  first_read_2:
    image: 'bitnami/postgresql:latest'
    container_name: read2
    ports:
      - 127.0.0.1:9002:5432
    depends_on:
      - first_write
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replication_user
      - POSTGRESQL_REPLICATION_PASSWORD=replication_password
      - POSTGRESQL_MASTER_HOST=localhost
      - POSTGRESQL_PASSWORD=database_password
      - POSTGRESQL_MASTER_PORT_NUMBER=9000
      - POSTGRESQL_PGAUDIT_LOG=READ,WRITE
    networks:
      - net

networks:
  net:
